### ISSUE TITLE
terrible

### ISSUE THREAD

**Issue by spifory** [osaka-lab/osaka-codec#1]

**Comment by ananasmoe** [comment]
![image](https://github.com/user-attachments/assets/6c257380-7e54-422a-b489-c4d5a3281525)

**Comment by spifory** [comment]
> ![image](https://private-user-images.githubusercontent.com/132799819/384356644-6c257380-7e54-422a-b489-c4d5a3281525.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNzAzNjcsIm5iZiI6MTczMTA3MDA2NywicGF0aCI6Ii8xMzI3OTk4MTkvMzg0MzU2NjQ0LTZjMjU3MzgwLTdlNTQtNDIyYS1iNDg5LWM0ZDVhMzI4MTUyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOFQxMjQ3NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZTNhNTU2ZGI4Njc4ZWIyZTcyODFmYjdiYTgwMTYzMWE5ZDEzMTRjODA4ZWQ4NzVmNGM4YjlhNjJmNzg5N2FmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.816qk5e1nHrrDwA-uJk2aw1rdqFXs1-IvzVHpx1r-9A)

![kill_you](https://github.com/user-attachments/assets/ccb7cbfe-5718-4dfa-8758-83d1e2b4c8d0)

**Comment by THEGOLDENPRO** [comment]
![image](https://github.com/user-attachments/assets/30631c40-d642-45f6-926b-a59db7530f58)
